#!/bin/bash
#SBATCH --job-name=columns_sweep
#SBATCH --output=/network/scratch/l/leo.gagnon/sbatch_output.txt
#SBATCH --error=/network/scratch/l/leo.gagnon/sbatch_error.txt
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --mem=8G
#SBATCH --gres=gpu

module load python/3.7
module load cuda/11.2/cudnn/8.1

source ~/columns/venv/bin/activate
cd ~/columns/src
wandb agent leogagnon/GLOM/t5dt9iks

